name:                isotope
version:             0.1.0.0
github:              "5FiftySix6/Isotope"
license:             GPL-3
author:              "Yusuf Bham"
maintainer:          "ybham6@gmail.com"
copyright:           "2019 Yusuf Bham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/5FiftySix6/Isotope#readme>

dependencies:
- base >= 4.7 && < 5
- time
- Cabal
- wreq
- bytestring
- lens
- aeson
- lens-aeson
- containers
- pretty-simple
- optparse-applicative
- async
- fuzzy 
- directory
- configurator

library:
  source-dirs: src

executables:
  isotope:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - isotope

tests:
  isotope-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - isotope
